import cors from 'cors'
import express, { type Request, type Response } from 'express'
import { createServer } from 'node:http'
import { mkdir, readFile, rename, stat, writeFile } from 'node:fs/promises'
import { createReadStream } from 'node:fs'
import path from 'node:path'
import multer from 'multer'
import { WebSocketServer, type WebSocket } from 'ws'

type Status = 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED'
type Stage = 'UPLOAD' | 'STT' | 'TEXT_RISK' | 'SCENE_DETECTION' | 'OCR' | 'MULTIMODAL' | 'FINALIZING' | 'COMPLETED'
type Severity = 'LOW' | 'MEDIUM' | 'HIGH'
interface EventBase { id: number; startMs: number; endMs: number; severity: Severity; reason: string; frameUrl: string | null }
type TimelineEvent = (EventBase & { type: 'SPEECH'; text: string; riskTypes: string[] }) | (EventBase & { type: 'CAPTION'; speechText: string; captionText: string })
interface VideoRecord { videoId: number; filename: string; uploadedAt: string; storagePath: string; mimeType: string; jobId: string; status: Status; progress: number; stage: Stage; message: string; errorCode?: string; report?: { videoId: number; jobId: string; status: 'COMPLETED'; summary: { high: number; medium: number; low: number }; events: TimelineEvent[] } }
interface State { nextVideoId: number; videos: Record<string, VideoRecord> }

const root = process.cwd(); const dataDir = process.env.MOCK_DATA_DIR ?? path.join(root, 'mock-data'); const uploadsDir = path.join(dataDir, 'uploads'); const statePath = path.join(dataDir, 'state.json'); const port = Number(process.env.PORT ?? 3001); const stepMs = Number(process.env.MOCK_STEP_MS ?? 900)
const stages: Stage[] = ['STT', 'TEXT_RISK', 'SCENE_DETECTION', 'OCR', 'MULTIMODAL', 'FINALIZING', 'COMPLETED']
let state: State = { nextVideoId: 1, videos: {} }; let failedOnce = false
const subscriptions = new Map<WebSocket, Map<string, string>>()

async function init() { await mkdir(uploadsDir, { recursive: true }); try { state = JSON.parse(await readFile(statePath, 'utf8')) as State } catch { await saveState() } }
async function saveState() { const temp = `${statePath}.tmp`; await writeFile(temp, JSON.stringify(state, null, 2)); await rename(temp, statePath) }
function success<T>(res: Response, status: number, message: string, data: T) { res.status(status).json({ success: true, message, data }) }
function failure(res: Response, status: number, code: string, message: string) { res.status(status).json({ success: false, message, error: { code, traceId: `mock-${Date.now().toString(36)}` } }) }
function video(id: string) { return state.videos[id] }
function mimeFor(filename: string) { const ext = path.extname(filename).toLowerCase(); return ext === '.mov' ? 'video/quicktime' : ext === '.avi' ? 'video/x-msvideo' : 'video/mp4' }
function reportFor(record: VideoRecord) { return { videoId: record.videoId, jobId: record.jobId, status: 'COMPLETED' as const, summary: { high: 2, medium: 2, low: 1 }, events: [{ id: 1, startMs: 3200, endMs: 6100, type: 'SPEECH' as const, severity: 'HIGH' as const, text: '이 표현은 특정 집단을 하나의 특성으로 단정할 수 있습니다.', riskTypes: ['GENERALIZATION'], reason: '특정 집단에 대한 일반화 표현이 포함되어 있습니다.', frameUrl: null }, { id: 2, startMs: 7310, endMs: 9220, type: 'CAPTION' as const, severity: 'MEDIUM' as const, speechText: '실제 발언은 비교적 중립적입니다.', captionText: '논란의 발언, 지금 확인하세요', reason: '화면 자막이 실제 발언보다 자극적으로 표현되었습니다.', frameUrl: `/api/v1/videos/${record.videoId}/frames/2` }, { id: 3, startMs: 12600, endMs: 15000, type: 'SPEECH' as const, severity: 'LOW' as const, text: '개인 경험을 설명하는 구간입니다.', riskTypes: ['CONTEXT'], reason: '맥락을 함께 확인하면 오해를 줄일 수 있는 구간입니다.', frameUrl: null }] } }
function publish(record: VideoRecord) { const destination = `/topic/videos/${record.videoId}/progress`; const payload = JSON.stringify({ videoId: record.videoId, jobId: record.jobId, status: record.status, progress: record.progress, stage: record.stage, message: record.message, errorCode: record.errorCode }); for (const [socket, topics] of subscriptions) { for (const [topic, subscriptionId] of topics) if (topic === destination && socket.readyState === socket.OPEN) socket.send(`MESSAGE\nsubscription:${subscriptionId}\ndestination:${destination}\ncontent-type:application/json\ncontent-length:${Buffer.byteLength(payload)}\n\n${payload}\u0000`) } }
async function advance(record: VideoRecord) { if (record.status === 'COMPLETED') return; record.status = 'PROCESSING'; record.message = '분석 준비 중'; await saveState(); publish(record); let index = Math.max(0, stages.indexOf(record.stage)); const timer = setInterval(async () => { const current = state.videos[String(record.videoId)]; if (!current || current.jobId !== record.jobId) { clearInterval(timer); return } if (process.env.MOCK_FAIL_FIRST_JOB === 'true' && !failedOnce && index >= 2) { failedOnce = true; current.status = 'FAILED'; current.errorCode = 'ANALYSIS_FAILED'; current.message = '텍스트 위험도 분석 중 오류가 발생했습니다.'; await saveState(); publish(current); clearInterval(timer); return } current.stage = stages[index] ?? 'COMPLETED'; current.progress = current.stage === 'COMPLETED' ? 100 : Math.min(95, Math.round(((index + 1) / stages.length) * 100)); current.message = current.stage === 'COMPLETED' ? '검수 결과가 준비되었습니다.' : stageMessage(current.stage); if (current.stage === 'COMPLETED') { current.status = 'COMPLETED'; current.report = reportFor(current); clearInterval(timer) } await saveState(); publish(current); index += 1 }, stepMs) }
function stageMessage(stage: Stage) { const messages: Partial<Record<Stage, string>> = { STT: '음성을 텍스트로 변환 중', TEXT_RISK: '발언의 맥락과 위험도 분석 중', SCENE_DETECTION: '장면 전환을 확인 중', OCR: '화면 자막 분석 중', MULTIMODAL: '발언과 화면을 함께 검토 중', FINALIZING: '검수 결과를 정리 중' }; return messages[stage] ?? '분석 중' }

const app = express(); app.use(cors()); app.use(express.json());
const upload = multer({ storage: multer.diskStorage({ destination: (_req, _file, cb) => cb(null, uploadsDir), filename: (_req, file, cb) => cb(null, `${Date.now()}-${file.originalname.replace(/[^a-zA-Z0-9._-]/g, '_')}`) }), limits: { fileSize: 500 * 1024 * 1024 }, fileFilter: (_req, file, cb) => { const ext = path.extname(file.originalname).toLowerCase(); cb(null, ['.mp4', '.mov', '.avi'].includes(ext)) } })
app.post('/api/v1/videos', (req, res) => { upload.single('file')(req, res, async (error) => { if (error instanceof multer.MulterError && error.code === 'LIMIT_FILE_SIZE') return failure(res, 413, 'MAX_UPLOAD_SIZE_EXCEEDED', '파일 크기가 500MB를 초과했습니다.'); if (error) return failure(res, 415, 'UNSUPPORTED_VIDEO_FORMAT', '지원하지 않는 영상 형식입니다.'); if (!req.file) return failure(res, 400, 'INVALID_REQUEST', '영상 파일을 첨부해 주세요.'); const id = state.nextVideoId++; const jobId = `job_${Math.random().toString(16).slice(2, 8)}`; const record: VideoRecord = { videoId: id, filename: req.file.originalname, uploadedAt: new Date().toISOString(), storagePath: req.file.path, mimeType: mimeFor(req.file.originalname), jobId, status: 'PENDING', progress: 0, stage: 'UPLOAD', message: '분석 요청을 준비 중' }; state.videos[String(id)] = record; await saveState(); success(res, 201, '영상 업로드 성공', { videoId: id, jobId, filename: record.filename, status: record.status, streamUrl: `/api/v1/videos/${id}/stream` }); void advance(record) }) })
app.get('/api/v1/videos', (_req, res) => { const items = Object.values(state.videos).sort((a, b) => b.videoId - a.videoId).map(record => ({ videoId: record.videoId, filename: record.filename, uploadedAt: record.uploadedAt ?? new Date(0).toISOString(), status: record.status, progress: record.progress, eventCount: record.report?.events.length ?? 0, streamUrl: `/api/v1/videos/${record.videoId}/stream` })); success(res, 200, '검수 이력 조회 성공', items) })
app.get('/api/v1/videos/:id/status', (req, res) => { const record = video(req.params.id); if (!record) return failure(res, 404, 'VIDEO_NOT_FOUND', '영상을 찾을 수 없습니다.'); success(res, 200, '분석 상태 조회 성공', { videoId: record.videoId, jobId: record.jobId, status: record.status, progress: record.progress, stage: record.stage, message: record.message, errorCode: record.errorCode }) })
app.get('/api/v1/videos/:id/report', (req, res) => { const record = video(req.params.id); if (!record) return failure(res, 404, 'VIDEO_NOT_FOUND', '영상을 찾을 수 없습니다.'); if (record.status !== 'COMPLETED' || !record.report) return failure(res, 409, 'ANALYSIS_NOT_COMPLETED', '분석이 아직 완료되지 않았습니다.'); success(res, 200, '분석 결과 조회 성공', record.report) })
app.post('/api/v1/videos/:id/analysis/retry', (req, res) => { const record = video(req.params.id); if (!record) return failure(res, 404, 'VIDEO_NOT_FOUND', '영상을 찾을 수 없습니다.'); if (record.status === 'PROCESSING' || record.status === 'PENDING') return failure(res, 409, 'ANALYSIS_IN_PROGRESS', '분석이 진행 중입니다.'); if (record.status !== 'FAILED') return failure(res, 409, 'INVALID_ANALYSIS_STATE', '실패한 분석만 다시 시작할 수 있습니다.'); record.jobId = `job_${Math.random().toString(16).slice(2, 8)}`; record.status = 'PENDING'; record.progress = 0; record.stage = 'UPLOAD'; record.message = '분석 재시작 요청이 접수되었습니다.'; delete record.errorCode; delete record.report; void saveState().then(() => advance(record)); success(res, 202, '분석 재시작 요청이 접수되었습니다.', { videoId: record.videoId, jobId: record.jobId, status: record.status }) })
app.get('/api/v1/videos/:id/stream', async (req, res) => { const record = video(req.params.id); if (!record) return failure(res, 404, 'VIDEO_NOT_FOUND', '영상을 찾을 수 없습니다.'); try { const info = await stat(record.storagePath); const range = req.headers.range; res.setHeader('Accept-Ranges', 'bytes'); res.setHeader('Content-Type', record.mimeType); if (!range) { res.setHeader('Content-Length', info.size); return createReadStream(record.storagePath).pipe(res) } const match = /bytes=(\d*)-(\d*)/.exec(range); if (!match) return failure(res, 416, 'RANGE_NOT_SATISFIABLE', '요청한 영상 범위를 읽을 수 없습니다.'); const start = match[1] ? Number(match[1]) : 0; const end = match[2] ? Number(match[2]) : info.size - 1; if (start >= info.size || end >= info.size || start > end) return failure(res, 416, 'RANGE_NOT_SATISFIABLE', '요청한 영상 범위를 읽을 수 없습니다.'); res.status(206).setHeader('Content-Range', `bytes ${start}-${end}/${info.size}`); res.setHeader('Content-Length', end - start + 1); return createReadStream(record.storagePath, { start, end }).pipe(res) } catch { return failure(res, 404, 'VIDEO_NOT_FOUND', '영상 파일을 찾을 수 없습니다.') } })
app.get('/api/v1/videos/:id/frames/:frameId', (req, res) => { if (!video(req.params.id)) return failure(res, 404, 'VIDEO_NOT_FOUND', '영상을 찾을 수 없습니다.'); if (req.params.frameId !== '2') return failure(res, 404, 'FRAME_NOT_FOUND', '프레임을 찾을 수 없습니다.'); const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAEAAAAAQCAYAAACqaXHeAAAAC0lEQVR42mNkYPgPAAEDAQAIWqD2AAAAAElFTkSuQmCC', 'base64'); res.type('png').send(png) })

const httpServer = createServer(app); const wss = new WebSocketServer({ noServer: true });
function parseFrame(raw: string) { const [head, body = ''] = raw.replace(/\u0000$/, '').split('\n\n'); const lines = head.split('\n'); const command = lines.shift() ?? ''; const headers = Object.fromEntries(lines.map(line => { const index = line.indexOf(':'); return [line.slice(0, index), line.slice(index + 1)] })); return { command, headers, body } }
wss.on('connection', (socket) => { subscriptions.set(socket, new Map()); socket.on('message', raw => { const frame = parseFrame(raw.toString()); if (frame.command === 'CONNECT' || frame.command === 'STOMP') socket.send('CONNECTED\nversion:1.2\nheart-beat:10000,10000\n\n\u0000'); if (frame.command === 'SUBSCRIBE' && frame.headers.destination) subscriptions.get(socket)?.set(frame.headers.destination, frame.headers.id ?? 'sub-0'); if (frame.command === 'UNSUBSCRIBE' && frame.headers.id) { const topics = subscriptions.get(socket); if (topics) for (const [topic, id] of topics) if (id === frame.headers.id) topics.delete(topic) } }); socket.on('close', () => subscriptions.delete(socket)); const heartbeat = setInterval(() => { if (socket.readyState === socket.OPEN) socket.send('\n'); else clearInterval(heartbeat) }, 10000) })
httpServer.on('upgrade', (request, socket, head) => { if (request.url !== '/ws') { socket.destroy(); return } wss.handleUpgrade(request, socket, head, ws => wss.emit('connection', ws, request)) })

await init(); for (const record of Object.values(state.videos)) if (record.status === 'PENDING' || record.status === 'PROCESSING') void advance(record); httpServer.listen(port, () => console.log(`Creator Risk mock server listening on http://localhost:${port}`))
